import pytest

from fixtures.clear_register import clear_register

from fixtures.clear_register_two import clear_register_two

from fixtures.clear_register_two_createdm import clear_register_two_createdm

from fixtures.clear_register_createchannel import clear_register_createchannel

from fixtures.clear_register_two_createchannel import clear_register_two_createchannel

from fixtures.clear_register_createchannel_sendmsg import clear_register_createchannel_sendmsg

from fixtures.clear_register_two_createchannel_twoowners import clear_register_two_createchannel_twoowners

from fixtures.clear_register_createchannel_send50msgs import clear_register_createchannel_send50msgs
