import pytest

from fixtures.clear_and_register_two import clear_and_register_two
from fixtures.clear_and_register_and_create_channel import clear_and_register_and_create_channel
from fixtures.clear_register_create_channel_send_message import clear_register_create_channel_send_message